### PR TITLE
Modified the code so it follows the latest official Nuxt's Module Author Guide and bumped the medusa package version

### PR DESCRIPTION
**Pull request by dimitrio-m**
Modified the code so it follows the latest official Nuxt's Module Author Guide and bumped the medusa package version.

- Updated the packages to recent versions recommended by the guide.
- Updated the npm scripts accordingly.
- Added a default tsconfig.json file for the playground client code.
- Added a default tsconfig.json file for the playground server code.
- Updated app.vue to follow linting rules.
- Updated module.ts to use the import type declaration.
- Added yarn run dev:prepare as a pre step to the prepack operation in the release script.
- Bumped @medusajs/medusa-js to the latest version.

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Hello @Baroshem as I said in the issue #31, I had a problem that seemed related to the npm package release. I tried to execute the module locally and it worked great, but I couldn't get it to work when importing the module as an npm package. I started to investigate and noticed that the module was not following the latest [Nuxt Module Author Guide](https://nuxt.com/docs/guide/going-further/modules), so I updated the packages, added some default configuration to TypeScript that the builder needed and finally tested the module by uploading it to an [npm registry ](https://www.npmjs.com/package/nuxt-medusa-test) (it was my first time doing that) and it worked. I imported the test package in the project that I had the issue with in the first place, and it was a success.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

I don't know if this changes are ok, or if we need to change another thing or do further testing (first time contributor here :smiley: ). I tried executing the tests and they passed. I also tried to execute the playground example and it worked great. I also tried the package in the project that I had the problem in the first place and it worked there too.

### CODE REVIEW

**Comment by Baroshem** [comment]
Hey,

Thanks for this PR! I will review it and give you some hints :)

**Review by Baroshem — COMMENTED** [review]
One small comment to resolve :)

**Comment by dimitrio-m** [comment]
> One small comment to resolve :)

That's right! That was an oopsie, I forgot to change back the name when I uploaded it to the npm registry for testing. Let me do a commit to fix it.

**Comment by Baroshem** [comment]
No worries Buddy. I am merging this PR and will release a new version soon! :)

**Pull request merged**
